<a href="https://colab.research.google.com/github/veager/StudyNotes/blob/new/Codes/PyTorch-Tutorial/PyTorch-%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E3%80%81%E5%BC%A0%E9%87%8F%E7%94%9F%E6%88%90%E3%80%81%E5%BC%A0%E9%87%8F%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch 数据类型、张量生成、张量操作

参考资料

- 博客：PyTorch 数据类型、张量生成、张量操作，[地址](https://www.cnblogs.com/veager/articles/16295702.html)

- Github：Codes/PyTorch-Tutorial/PyTorch-数据类型、张量生成、张量操作.ipynb

In [ ]:
import torch
import torch.nn as nn

In [ ]:
tensor = torch.tensor([1., 2.,], requires_grad=True)

print(tensor.data)
print(tensor.grad)


w = nn.Parameter(torch.tensor([1., 2.,]))

print(w.data)
print(w.grad)

tensor([1., 2.])
None
tensor([1., 2.])
None


`Tensor.data` 属性 和 `Tensor.detach()` 方法

In [ ]:
tensor = torch.tensor([1., 2.,], requires_grad=True)

tensor_1 = tensor.detach()
tensor_2 = tensor.data
print(tensor, tensor_1, tensor_2)

tensor_1 = tensor_1 + tensor_1
tensor_2 = tensor_2 + tensor_2
print(tensor, tensor_1, tensor_2)

tensor([1., 2.], requires_grad=True) tensor([1., 2.]) tensor([1., 2.])
tensor([1., 2.], requires_grad=True) tensor([2., 4.]) tensor([2., 4.])
