<a href="https://colab.research.google.com/github/veager/StudyNotes/blob/new/Codes/PyTorch-Tutorial/PyTorch-torch.nn%E6%A8%A1%E5%9D%97-Layer%E6%80%BB%E7%BB%93.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch torch.nn 模块 - Layer 总结

参考资料

- 博客：PyTorch torch.nn 模块 - Layer 总结, [site](https://www.cnblogs.com/veager/articles/16291933.html)

- Github：Codes/PyTorch-Tutorial/PyTorch-torch.nn模块-Layer总结.ipynb


# 0 概述

In [58]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 1 通用层和容器层（Containers）

# 2 线性层

# 3 激活函数

## 3.1 Sigmoid 

In [59]:
input = torch.rand((3, 5))

output_1 = nn.Sigmoid()(input)

print(output_1.size())
print(torch.sum(output_1, dim=1))
# Output: tensor([1., 1., 1.])

# 等价形式：torch.sigmoid() 或 F.sigmoid()
output_2 = torch.sigmoid(input)
output_3 = F.sigmoid(input) 
# 使用 F.sigmoid() 会输出 UserWarning 信息
# UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
print(torch.sum(torch.abs(output_2 - output_1)), 
      torch.sum(torch.abs(output_3 - output_1)))

torch.Size([3, 5])
tensor([3.1894, 3.1061, 3.0443])
tensor(0.) tensor(0.)


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


## 3.2 Softmax 

In [60]:
input = torch.rand((3, 5))

output_1 = nn.Softmax(dim=1)(input)

print(output_1.size())
print(torch.sum(output_1, dim=1))
# Output: tensor([1., 1., 1.])

# 等价形式：torch.softmax() 或 F.softmax()
output_2 = torch.softmax(input, dim=1)
output_3 = F.softmax(input, dim=1)
print(torch.sum(torch.abs(output_2 - output_1)), 
      torch.sum(torch.abs(output_3 - output_1)))

torch.Size([3, 5])
tensor([1., 1., 1.])
tensor(0.) tensor(0.)


# 4 损失函数

## 4.1 回归损失

- `reduction` 参数

- `nn.MSELoss` 类 和 `F.mse_loss()` 函数

- `nn.L1Loss` 类 和 `F.l1_loss()` 函数

In [61]:
input = torch.randn(3, 5)
target = torch.randn(3, 5)

# 损失函数 1：reduction='mean'
output_1 = nn.MSELoss()(input, target)

# 损失函数 2：reduction='none'
output_2 = nn.MSELoss(reduction='none')(input, target)

# 输出
print(output_1.size(), output_1)
print(output_2.size(), output_2)
# Output 1：torch.Size([]) tensor(1.1773)
# Output 2：torch.Size([3, 5]) tensor([[...

torch.Size([]) tensor(2.8110)
torch.Size([3, 5]) tensor([[1.2228e+01, 1.7304e+00, 1.0846e-03, 6.3876e-03, 2.3148e+00],
        [1.0003e+00, 3.7505e-02, 1.9426e+00, 4.0366e+00, 8.6523e+00],
        [3.6143e-01, 4.1810e-04, 1.3871e+00, 5.0096e+00, 3.4567e+00]])


## 4.2 二分类损失

- `nn.BCEWithLogitsLoss()` 层和 `F.binary_cross_entropy_with_logits()` 函数

- `nn.BCELoss()` 层 `F.binary_cross_entropy()` 函数

In [62]:
torch.manual_seed(42)

input = torch.rand(5)   
target = torch.empty(5).random_(2)
print(input, target)

# 方式一：nn.BCEWithLogitsLoss()
output_1 = nn.BCEWithLogitsLoss()(input, target)
print(output_1)

# 方式二：nn.Sigmoid() + nn.BCELoss()
input_2 = nn.Sigmoid()(input)
output_2 = nn.BCELoss()(input_2, target)
print(output_2)

# 方式三：F.binary_cross_entropy_with_logits() 
output_3 = F.binary_cross_entropy_with_logits(input, target)
print(output_3)

# 方式四：torch.sigmoid() + F.binary_cross_entropy()
input_4 = torch.sigmoid(input)
output_4 = F.binary_cross_entropy(input_4, target)
print(output_4)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904]) tensor([1., 0., 0., 0., 1.])
tensor(0.8603)
tensor(0.8603)
tensor(0.8603)
tensor(0.8603)


## 4.3 多分类损失函数

- `nn.CrossEntropyLoss()` 层和函数 `F.cross_entropy()` 函数

- `nn.NLLLoss()` 层和函数 `F.nll_loss()` 函数



In [63]:
torch.manual_seed(0)

input = torch.randn(7, 3)
target = torch.empty(7, dtype=torch.long).random_(3)
print(input)
print(target)

# 方式 1：nn.CrossEntropyLoss()
output_1 = nn.CrossEntropyLoss()(input, target)
print(output_1)
# Output tensor(1.4895)

# 方式 2：nn.LogSoftmax() + nn.NLLLoss() 
input_2 = nn.LogSoftmax(dim=1)(input)
output_2 = nn.NLLLoss()(input_2, target)
print(output_2)
# Output tensor(1.4895)

# 方式 3：cross_entropy()
output_3 = F.cross_entropy(input, target)
print(output_3)

# 方式 4：torch.log_softmax() + F.nll_loss()
input_4 = torch.log_softmax(input, dim=1)
output_4 = F.nll_loss(input_4, target)
print(output_4)

tensor([[-1.1258, -1.1524, -0.2506],
        [-0.4339,  0.8487, -1.5551],
        [-0.3414,  1.8530,  0.4681],
        [-0.1577,  1.4437,  0.2660],
        [ 0.1665,  1.5863,  0.9463],
        [-0.8437,  0.9318,  1.2590],
        [ 2.0050,  0.0537,  0.6181]])
tensor([2, 2, 1, 2, 0, 1, 1])
tensor(1.4895)
tensor(1.4895)
tensor(1.4895)
tensor(1.4895)
